name: Update Tariff 15 TEST

on:
  schedule:
    - cron: '*/5 * * * *'  # КАЖДЫЕ 5 МИНУТ!
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install requests
    - run: python update_tariff15_improved.py
    - run: |
        git config user.name "vpn-bot"
        git config user.email "bot@vpn.com"
        git add tariff15.txt
        if git diff --staged --quiet; then
          echo "Нет изменений"
        else
          git commit -m "🧪 TEST Update tariff15 $(date)"
          git push
        fi
